-- MySQL Script generated by MySQL Workbench
-- Пн. 07 дек. 2015 19:10:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WarOfViruses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WarOfViruses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WarOfViruses` DEFAULT CHARACTER SET utf8 ;
USE `WarOfViruses` ;

-- -----------------------------------------------------
-- Table `WarOfViruses`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarOfViruses`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `googleToken` VARCHAR(100) NOT NULL,
  `userType` INT NOT NULL,
  `nicknameStr` VARCHAR(45) NOT NULL,
  `nicknameId` VARCHAR(45) NOT NULL,
  `color` INT UNSIGNED NOT NULL,
  `invitationTarget`  NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `googleToken_UNIQUE` (`googleToken` ASC),
  INDEX `fkIvitation_idx` (`invitationTarget` ASC),
  CONSTRAINT `fkIvitationTarget`
    FOREIGN KEY (`invitationTarget`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Device` (
  `token` VARCHAR(100) NOT NULL,
  `user`  NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `user_idx` (`user` ASC),
  CONSTRAINT `fkDeviceOwner`
    FOREIGN KEY (`user`)
    REFERENCES `WarOfViruses`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Contacts` (
  `user` INT UNSIGNED NOT NULL,
  `friend` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user`, `friend`),
  CONSTRAINT `fkFriends`
    FOREIGN KEY (`user` , `friend`)
    REFERENCES `WarOfViruses`.`User` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Game` (
  `id` INT UNSIGNED NOT NULL,
  `playerCrosses` INT UNSIGNED NOT NULL,
  `playerZeroes` INT UNSIGNED NOT NULL,
  `isFinished` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkPlayers_idx` (`playerCrosses` ASC, `playerZeroes` ASC),
  CONSTRAINT `fkPlayers`
    FOREIGN KEY (`playerCrosses` , `playerZeroes`)
    REFERENCES `WarOfViruses`.`User` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WarOfViruses`.`Turn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WarOfViruses`.`Turn` (
  `game` INT UNSIGNED NOT NULL,
  `turnNo` INT UNSIGNED NOT NULL,
  `type` INT NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  PRIMARY KEY (`game`, `turnNo`),
  CONSTRAINT `fkTurns`
    FOREIGN KEY (`game`)
    REFERENCES `WarOfViruses`.`Game` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
